sonar.projectKey=Fast-Api-Sonnar
sonar.projectName=Fast-Api-Sonnar
sonar.sources=src,routes,public,bin
sonar.tests=tests
sonar.test.inclusions=tests/**/*.js
sonar.exclusions=node_modules/**,coverage/**,docs/**,k6/**,.github/**,public/stylesheets/**
sonar.sourceEncoding=UTF-8
